### ISSUE TITLE
Fix Contract ID link on NFT details page for new legion collections

### ISSUE THREAD

**Issue by wyze** [TreasureProject/treasure-marketplace#156]
### Describe the bug

![](https://media.discordapp.net/attachments/884676559049478174/939647751849902150/unknown.png)

### Steps to reproduce

View detail page for a Genesis Common.

### Expected behavior

I would expect the link to take me to the arbiscan page. 

### How often does this bug happen?

Every time

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by asharma13524** [comment]
I believe `getExplorerAddressLink` is deprecated. Will update to `Arbitrum.getExplorerTransactionLink()`

the following addresses do not look correct to me in `src/lib/hooks.ts` . 

```
{
      name: "Legion Auxiliary",
      address: "0xfe8c1ac365ba6780aec5a985d989b327c27670a1-1",
    },
    {
      name: "Legion Genesis",
      address: "0xfe8c1ac365ba6780aec5a985d989b327c27670a1-0",
    },
    // Recruits
    {
      name: "Legions",
      address: "0xfe8c1ac365ba6780aec5a985d989b327c27670a1-2",
    },
```

can we confirm the correct addresses?
