### ISSUE TITLE
Compare floor price description off for Consumables

### ISSUE THREAD

**Issue by wyze** [TreasureProject/treasure-marketplace#158]
![image](https://user-images.githubusercontent.com/186971/152683529-befede3f-9b04-4eaf-bf1d-9e547f447cb1.png)

**Comment by asharma13524** [comment]
can tackle this one. The total listings is off as well
![Screen Shot 2022-02-11 at 2 14 33 PM](https://user-images.githubusercontent.com/28710772/153655039-d9d91fc7-7c86-4054-b6ea-8002eacbb76b.png)
