### ISSUE TITLE
Smolbrains search shows all smols when adding 2 traits to search by in the same section

### ISSUE THREAD

**Issue by dsldsl** [TreasureProject/treasure-marketplace#166]
### Describe the bug

Smolbrains search works correctly when searching for 1 trait with 1 selection, but shows all smols when adding 2 selections for the same traits to search by.

### Steps to reproduce

1) Go to Smolbody marketplace.  
2) Filter by a body color.  See search correct.
3) Filter by a second body color.  See all smols show up in results.

(This happens for other traits as well)

### Expected behavior

As a user, I expect to see smols who have one of the two body colors I am searching for, but I see all smols.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Crome
- Version: [e.g. 91.1]

### Additional context

not a high priority for me, just fyi

**Comment by dsldsl** [comment]
![image](https://user-images.githubusercontent.com/50015/153543982-a92e16c5-f7f8-4b81-805e-ae96830f84d6.png)

![image](https://user-images.githubusercontent.com/50015/153544011-1eb7dc9e-ff2b-4637-b766-8f9edb83e423.png)

![image](https://user-images.githubusercontent.com/50015/153544037-b8761416-0fd6-4321-a0dd-af121ea6857c.png)

**Comment by wyze** [comment]
This will be fixed in #164. I am reordering how we get the data as if you do something with a large dataset, say `Gender: male`, it doesn't handle that. Should get it fixed today.

**Comment by dsldsl** [comment]
Awesome! thank you

**Comment by wyze** [comment]
Should be good to go now!
