### ISSUE TITLE
Clicking "back" from detail view of an item in the treasure forgets the current filter

### ISSUE THREAD

**Issue by dsldsl** [TreasureProject/treasure-marketplace#177]
### Describe the bug

When i'm searching for Tier 4 treasures and I click into a detail view on an item, when I go back it forgets I was in Tier 4 and I have to filter again

### Steps to reproduce

Go to Treasure collection
Filter for Tier 4
Click on an item
Click back using the top left arrow
See that you're no longer in tier 4 items

### Expected behavior

As a user, when I am searching for Tier 4 items, I expect the search filter to stay active after I have clicked into an item and go back

### How often does this bug happen?

Every time

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by alecananian** [comment]
Updating the collection page URL with query parameters for the selected filters could resolve this. It would also allow for bookmarking/deep-linking to an already filtered page, which I think would be useful (functionality you can see on OpenSea, for example)

**Comment by alecananian** [comment]
> It actually already does have the filters in the url for the collection filtering, but the item page is hard linking back to the original collection page. Could be as simple as changing "back to collection" to send a browser back link but that would chance the existing functionality from the activity page from which "back to collection" sends you to the collection page. (intentionally? probably ok to change) or could pass the query string through to the item page for backref purposes.

Hah sorry, I _just_ deleted my comment because I misunderstood the issue. The back button approach would work, unless you landed on the item detail page directly.

**Comment by dsldsl** [comment]
:)

Alternatively, could just remove the link altogether and just have people use the browser back button to go back, wdyt?  (how it works on OS currently)

**Comment by davidagustin** [comment]
This appears to be this issue?  https://github.com/TreasureProject/treasure-marketplace/issues/210

**Comment by davidagustin** [comment]
Should there be a session or local storage to help with this problem?

**Comment by alecananian** [comment]
Closing as won't fix - this repository will be archived with the move to Trove
