### ISSUE TITLE
Trying to "delist" an asset in my "inactive" list so that it doesn't auto list in the future gets an error

### ISSUE THREAD

**Issue by dsldsl** [TreasureProject/treasure-marketplace#189]
### Describe the bug

The message on the inactive listings tab suggests I should delist them if I dont want to auto list in the future.  When I try to do that, I get an error.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/50015/155447381-dff025e6-983f-41b9-bdd1-29b8b208af68.png">

### Steps to reproduce

..

### Expected behavior

..

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by wyze** [comment]
Like the message says, you have to own the item (needs to be in your wallet) to cancel the listing. If this is something you staked, when it comes back, it will still be inactive and give you a chance to cancel the listing then.

**Comment by dsldsl** [comment]
what's the point then of the other message on the delisted header that says
I should delist the item if I dont want it to be sold / listed when it
comes back?

**Comment by wyze** [comment]
It will remain inactive when it comes back. Also, staking for Smol Brains/Bodies while they were in the Gym/School didn't leave the wallet, so they were able to delist at that time.

**Comment by dsldsl** [comment]
Hm. Ok. This was for a consumable I consumed fyi

**Comment by wyze** [comment]
Going to close this. Since we are switching marketplace contracts, all Inactive and Active listings will be removed. The new contract has the ability to cancel a listing even if you do not own the NFT.
