### ISSUE TITLE
All orders are front-runnable [SECURITY] [CRITICAL]

### ISSUE THREAD

**Issue by fulldecent** [TreasureProject/treasure-marketplace#192]
### Describe the bug

The owner of any token can change the sale price AFTER a buyer has committed to buy an NFT.

This means if you execute an order to buy an NFT at 1 Ether, by the time it settles your actual price may be 100 Ether.

How: simply insert an `updateListing` call before the order goes through.

**Comment by minebuu** [comment]
The old contract (TreasureMarketplaceBuyer.sol) has a buyItem with no price parameter, but the other contract (TreasureMarketplaceBuyer.sol) has a buyItem with _pricePerItem parameter. The attack can be applied to the later function in TreasureMarketplaceBuyer.sol?

**Comment by wyze** [comment]
This has been fixed in the latest contract we will be deploying. Thank you!

**Comment by fulldecent** [comment]
I could be appropriate to recognize this and other security issues by putting a warning at the top of README.md.

This could prevent harm to other people studying this contract that is currently published.
