### ISSUE TITLE
Input for autocomplete does not lose focus after selecting an option

### ISSUE THREAD

**Issue by davidagustin** [TreasureProject/treasure-marketplace#208]
### Describe the bug

The focus does not go away after selecting an option from autocomplete. The user has to the click away from the autocomplete dropdown and click again into the input to trigger the autocomplete dropdown again.

### Steps to reproduce

1. Click on the input in search component located at the header
2. Select an option

### Expected behavior

Selecting an option should lose focus from the input

### Screenshots or Videos

https://user-images.githubusercontent.com/30575095/159137069-16847dbd-f3ad-4bb9-92f4-63bd49a023ac.mov

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by davidagustin** [comment]
@jcheese1 @wyze

**Comment by wyze** [comment]
Closed via https://github.com/TreasureProject/treasure-marketplace/commit/6241e67aacde13af7a9f8cb2d0b00799110f7cc3
