### ISSUE TITLE
State is not persistent when clicking back to collection after viewing an item from the filter

### ISSUE THREAD

**Issue by cbh4ou** [TreasureProject/treasure-marketplace#210]
### Describe the bug

When you use a filter on the collection page and go to item's page then revert back to the collection the state does not persist. 

### Steps to reproduce

Filter Applied
![image](https://user-images.githubusercontent.com/29964356/159379964-fd0605c0-c0f3-420d-b1ef-0b192c78de8c.png)
Clicked on Item to see its page
![image](https://user-images.githubusercontent.com/29964356/159379982-17c4b223-0a3b-4fea-8e10-b2eaaacd1347.png)
Reverting back to Collection the Filter doesn't persist 
![image](https://user-images.githubusercontent.com/29964356/159379996-9d009a51-8b8a-40a7-ae7f-2f4d5d30cb7d.png)

### Expected behavior

The filter should persist so that users of the marketplace do not have to keep applying the same filters, at times users want to compare items chosen by traits and when the attributes do not persist it causes users to spend alot of time resetting the filters each time they go back. 

### How often does this bug happen?

Every time

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by cbh4ou** [comment]
May help to include the filters the user used above the items, so they do not have to scroll through a large collection of attributes to figure out which were applied.

**Comment by alecananian** [comment]
Closing as won't fix - this repository will be archived with the move to Trove
