### ISSUE TITLE
Toadstool Itemz searchFilter not working correctly

### ISSUE THREAD

**Issue by magiclars-off** [TreasureProject/treasure-marketplace#291]
### Describe the bug

In the Toadstoolz Items collection, try searching for the 'Iron Axe', 'Iron', 'I', 'Axe'  or whatever. Nothing shows up.

Issue is that for this specific collection the subgraph is returning null for `token > name`.

![image](https://user-images.githubusercontent.com/62888804/172593511-3500b540-d913-4308-a6a9-9457ce07c5c2.png)

### Steps to reproduce

1. Go To: https://marketplace.treasure.lol/collection/toadstoolz-itemz
2. Search: 'Iron', hit enter
3. nothing shows up

### Expected behavior

I expected to see Iron axe

### How often does this bug happen?

Every time

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by alecananian** [comment]
Closing as won't fix - this repository will be archived with the move to Trove, and the marketplace subgraph will be deprecated
