### ISSUE TITLE
Image/attributes not loading

### ISSUE THREAD

**Issue by Kevin-Mok** [TreasureProject/treasure-marketplace#72]
### Describe the bug

In the marketplace, images are not showing up. In the item page, no attributes are shown.

### Steps to reproduce

- [Smol Body market page](https://marketplace.treasure.lol/collection/0x17dacad7975960833f374622fad08b90ed67d1b5)
- [Smol Body token page](https://marketplace.treasure.lol/collection/0x17dacad7975960833f374622fad08b90ed67d1b5/3019)

### Expected behavior

Images/attributes should be visible at all times. 

### How often does this bug happen?

Sometimes

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/25857736/147890240-fcaca0a3-3b10-40c7-98f7-379f87af1155.png)

### Platform

- **OS**: Linux
- **Browser**: Firefox
- **Version**: 95

### Additional context

There is no issue with the [metadata](https://treasure-marketplace.mypinata.cloud/ipfs/Qmbt6W9QB74VZzJfWbqG7vi2hiE2K4AnoyvWGFDHEjgoqN/3019/0)/[image](https://treasure-marketplace.mypinata.cloud/ipfs/Qmbt6W9QB74VZzJfWbqG7vi2hiE2K4AnoyvWGFDHEjgoqN/3019/0.png) availability, which I could access directly.

**Comment by Kevin-Mok** [comment]
@wyze response to bug report on Discord:
> wyze — Today at 4:27 PM 
> Yes. It’s how the graph works. It fails to fetch from ipfs at times
> I’ve coded it to try and refetch when it transfers. This doesn’t seem like a good solution anymore. So will try something different going forward
> whenever a smolbody is transferred/bought/sold. It tries to refetch.

I might be interested in working on this issue if it's not a priority. If so, where could I start looking to fix this?

**Comment by jcheese1** [comment]
@Kevin-Mok hey, thanks for raising this. This is most likely a subgraph issue, so head to https://github.com/TreasureProject/treasure-marketplace-subgraph and raise it again there. @wyze will help you out :D

**Comment by Kevin-Mok** [comment]
@jcheese1, opened. https://github.com/TreasureProject/treasure-marketplace-subgraph/issues/43
