### ISSUE TITLE
Show `Staked` tab if user has staked NFTs with Listings

### ISSUE THREAD

**Issue by wyze** [TreasureProject/treasure-marketplace#87]
### Discussed in https://github.com/TreasureProject/treasure-marketplace/discussions/86

<div type='discussions-op-text'>

<sup>Originally posted by **wyze** January  5, 2022</sup>
No reason to show it if there is nothing there.</div>

**Comment by Caranell** [comment]
Hi @wyze. I wanted to help with this issue, but encountered multiple problems I'd like to discuss:

1. "hidden" tab was renamed to "staked" (pr #93), which was confusing at first
   1.1. Probably it should be also renamed on the backend? Cause atm there're multiple names referring to the same entity
  ```js
 case "staked":
        return [hidden, totals, updates, "No staked listings 🙂"] as const;
``` 
2. I think it's not as easy as it looks like in the current component's structure. Tabs are stored in a constant object, and shown before inventory data is fetched. There're two options to hide one of the tabs, either wait for the inventory data to load and only then show the non-empty tabs, or hide tabs after fetching data (which might cause tabs repositioning). Both of these cases might degrade UX, what do you think?

**Comment by wyze** [comment]
Maybe a better way to say it is, show the `Staked` tab if applicable. I've reworded the title to reflect that.

We are trying to phase it out, so I think leaving it as hidden in the query would be okay.

Here are the steps I would take:

1. Rename `tabs` to `defaultTabs`
2. Remove `Staked` from `defaultTabs`
3. Around this line, I would add logic for checking the data response: https://github.com/TreasureProject/treasure-marketplace/blob/821a0e6213a875fb9e0e93236ce3ae03592576a9/src/pages/inventory/%5B%5B...section%5D%5D.tsx#L599

```ts
  const tabs = useMemo(() => (data.hidden?.length ?? 0) > 0 ? [...defaultTabs, { name: "Staked", href: "/inventory/staked" }] : defaultTabs, [data.hidden])
```
